### ISSUE TITLE
Problem with this theme

### ISSUE THREAD

**Issue by giggioman00** [george-fb/tiny_manga#1]
Hi, I installed your theme in my site. My as you can see here: bit.ly/1TAWnwz

The alphabetical list is dropped at the letter B. Could you please tell me how to fix?

**Comment by george-fb** [comment]
It's because it's limited to 25 results. You have to change `$comics->order_by('name', 'ASC')->get_paged($page, 25);` to `$comics->order_by('name', 'ASC')->get_paged($page, 99999);` in `/application/controllers/reader.php`.

Don't think i can do this in the theme and a pagination won't look nice with the current layout.
Will try to do something about it.

**Comment by giggioman00** [comment]
Thank you. Just another question. I replaced this code in style.css:
```
body{
	background: url(assets/images/bg.png) fixed;/* Background pattern from subtlepatterns.com */
}
```

with this: 
```
body{
	background-color: #00ff00;
}
```

but still I see the old images. There is any other setting to change for replace the background?

**Comment by george-fb** [comment]
To me it's changed, try a CTRL+F5.

**Comment by giggioman00** [comment]
Nothing, still I see the old image

**Comment by george-fb** [comment]
I don't know, when i visit your site i get a white background.

Also i changed the `content/themes/tiny_manga/assets/js/tiny.js` file, add 

```
$('.navbar-toggle').click(function(){
 	$('.navbar-collapse').slideToggle();
});
```
after `window.addEventListener("orientationchange", function() { Masonry(); });`

https://github.com/george-fb/tiny_manga/commit/b0cf392a1b6d2d72ff01f303f10746a5c5034bad#diff-39849ebf6b9d21fc0aff645861360bbf

**Comment by giggioman00** [comment]
I think I have found the problem.
In the source url I get this css: 
style.css?v=0.8.19
And this css have the old bg.png image.
If I remove the part ?v=0.8.19
Or if I change from 0.8.19 to 0.8.20, I in the css I get the news background.
So, of can I remove/change that line in the source?

**Comment by george-fb** [comment]
Yes. That's just for caching, changing the version forces the browser to download the new file.
